apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-service
  namespace: default
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webcounter
  name: webcounter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webcounter
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webcounter
    spec:
      containers:
      - image: cfreire70/webcounter
        env:
        - name: REDIS_URL
          value: redis-service
        name: webcounter
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webcounter  
  name: webcounter-service
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31555
  selector:
    app: webcounter  
  type: NodePort 